### ISSUE TITLE
Only showing IP address

### ISSUE THREAD

**Issue by LordDarkneo** [ultrara1n/MiToolkit#25]
Hi,
the 1.6 version only shows the ip address of the robot, and not the token.
I am on OP6T. App Mihome version 5.4.61.
MiToolkit on Win7.
Thanks for your support (I got no error message)

**Comment by leafkicker** [comment]
Install an older mi home app from apkmirror, that worked for me.

**Comment by LordDarkneo** [comment]
Fixed by downloading the 5.0.9 beta version
