### ISSUE TITLE
Feature Request: Show IP/MAC in output

### ISSUE THREAD

**Issue by mouth4war** [ultrara1n/MiToolkit#4]
Hi @ultrara1n, Thanks for this useful utility. Would it be possible to show IP and MAC addresses in the output separated by commas? This will make it really useful for home automation users where we need both IP and token.

Thanks!

**Comment by ultrara1n** [comment]
Of course, this is no big deal. New Version will be online in around 2 hours.

**Comment by mouth4war** [comment]
Hi @ultrara1n Could you add a new release please?

**Comment by mouth4war** [comment]
Is there a timestamp field for when device was added? That would be great too.

**Comment by ultrara1n** [comment]
IP is now available, there is no record of the timestamp when the device was added :(.
